config/routes.rb
Rails.application.routes.draw do

  resources :ad_accounts, only: [:index, :show]

  namespace :data_source do
    namespace :ad_accounts do
      get 'custom_audiences/:id', to: "custom_audiences#show", as: "custom_audience"
      post "custom_audiences", to: "custom_audiences#create"
      post "custom_audiences/workflows"
      namespace :custom_audiences do
        post "uploads", to: "uploads#create"
      end
    end
  end

  get "/auth/facebook", as: "facebook_login"
	get '/auth/:provider/callback', to: 'sessions#create'

  delete "sessions/destroy", as: :logout

  namespace :api do
    post 'maropost_update', to: 'maropost#update'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/custom_audience.rb
class CustomAudience < ApplicationRecord
  has_many :workflows
  belongs_to :user

  def workflow_ids
    workflows.pluck(:mp_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authentications
  has_many :custom_audiences

  def most_recent_authentication
    authentications.order(updated_at: :desc).first
  end

  def token
    most_recent_authentication.token
  end
end

app/models/workflow.rb
class Workflow < ApplicationRecord
  belongs_to :custom_audience

  def custom_audience_id
    custom_audience.id
  end
end

app/controllers/ad_accounts_controller.rb
class AdAccountsController < LoggedInController
  def index
    @ad_accounts = []
    @ad_accounts.push get_ad_accounts_edge("me")
    businesses = graph.get_connections("me", "businesses")
    businesses.each do |business|
      begin
        @ad_accounts.push get_ad_accounts_edge(business["id"])
      rescue StandardError => ex
        Rails.logger.info ex
      end
    end
    @ad_accounts.flatten!
    @ad_accounts.each { |act| act["id"] ||= "act_#{act['account_id']}" }
    @ad_accounts.uniq! { |act| act["id"] }
  end

  def show
  end

  private

  def get_ad_accounts_edge(fb_id)
    graph.get_connections(fb_id, "adaccounts",
      fields: [:name, :business, :amount_spent, :account_status, :age])
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::API
end

app/controllers/api/maropost_controller.rb
class Api::MaropostController < Api::ApiController
  def update
    ProcessMaropostJourneyJob.perform_later(params.to_unsafe_h)
    head :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    if !session[:user_id].nil?
      @current_user ||= User.where(id: session[:user_id]).first
    end
  end

  def graph
    if current_user
      token = current_user.token
      graph = Koala::Facebook::API.new(token)
    else
      raise "User is not logged in"
    end
  end
end

app/controllers/data_source/ad_accounts/custom_audiences/uploads_controller.rb
class DataSource::AdAccounts::CustomAudiences::UploadsController < LoggedInController
  def create
  end
end

app/controllers/data_source/ad_accounts/custom_audiences_controller.rb
class DataSource::AdAccounts::CustomAudiencesController < LoggedInController
  layout false

  def show
    @results = []
    begin
      ad_act = params[:id]
      custom_audiences = graph.get_connections(ad_act, "customaudiences",
        fields: [:name, :description, :approximate_count, :operation_status, :delivery_status]
      )
      @results += custom_audiences.map { |data|
        id = data["id"]
        lut = current_user.custom_audiences.where(fb_id: id).first_or_create
        workflow_ids = lut&.workflow_ids || NullObject.get
        {
          id: id,
          ad_act_id: ad_act,
          name: data["name"],
          description: data["description"],
          approximate_count: data["approximate_count"],
          operation_status: data["operation_status"]["description"],
          delivery_status: data["delivery_status"]["description"],
          workflow_ids: workflow_ids
        }
      }
    rescue StandardError => ex
      Rails.logger.info ex
      render text: ex
    end
  end

  def create
    begin
      ad_act_id = params[:custom_audience][:ad_act_id]
      ca_name = params[:custom_audience][:name]
      graph.put_connections(ad_act_id, "customaudiences", name: ca_name, subtype: "CUSTOM")
      redirect_back fallback_location: root_url, notice: "Custom Audience created!"
    rescue StandardError => ex
      Rails.logger.info ex
      render text: ex
    end
  end

  def workflows
    parameters = params[:add_workflow_ids_to_custom_audience]
    workflow_ids = parameters[:workflow_ids].split(",").map(&:strip)
    custom_audience_id = parameters[:custom_audience_id]
    model = current_user.custom_audiences.where(fb_id: custom_audience_id).first
    model.workflows = workflow_ids.map { |id| model.workflows.where(mp_id: id).first_or_create }
    model.save!
    redirect_back fallback_location: root_url, notice: "Workflow IDs saved!"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to ad_accounts_path
    end
  end
end

app/controllers/logged_in_controller.rb
class LoggedInController < ApplicationController
  before_action :require_login

  def require_login
    if current_user.nil?
      redirect_to root_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	if params[:provider] == "facebook"
      auth_hash = request.env["omniauth.auth"]
      provider = auth_hash["provider"]
      uid = auth_hash["uid"]
      token = auth_hash["credentials"]["token"]

      authentication = Authentication.where(provider: provider, uid: uid).first
      if authentication
        @current_user = user = authentication.user
        session[:user_id] = user.id
      else
        user = User.create
        authentication = user.authentications.create(provider: provider, uid: uid)
      end

      authentication.token = token
      authentication.save!
    end

    redirect_to original_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_back fallback_location: root_url, notice: "Signed out!"
  end

  private

  def original_url
    request.env['omniauth.origin'] || root_url
  end
end

app/helpers/ad_accounts_helper.rb
module AdAccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_source/ad_accounts/custom_audiences/uploads_helper.rb
module DataSource::AdAccounts::CustomAudiences::UploadsHelper
end

app/helpers/data_source/ad_accounts/custom_audiences_helper.rb
module DataSource::AdAccounts::CustomAudiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logged_in_helper.rb
module LoggedInHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/ad_accounts/index.html.erb
<div class="container">
  <h1>Select an account</h1>
  <table class="table table-hover">
    <thead>
      <th>Account ID</th>
      <th>Name</th>
      <th>Business</th>
      <th>Amount Spent</th>
      <th>Age</th>
      <th></th>
    </thead>
    <tbody>
    <% @ad_accounts.each do |act| %>
      <tr data-href="<%= ad_account_path(act.dig('id')) %>">
        <td><%= act.dig("id") %></td>
        <td><%= act.dig("name") %></td>
        <td><%= act.dig("business", "name") %></td>
        <td><%= number_to_currency(act.dig("amount_spent").to_f / 100) %></td>
        <td><%= act.dig("age") %></td>
        <td><i class="fa fa-arrow-right"></i></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% console if Rails.env.development? %>

app/views/ad_accounts/show.html.erb
<div class="container">
  <div id="custom-audiences" data-path="<%= data_source_ad_accounts_custom_audience_path(params[:id]) %>">
  </div>

  <%= link_to "Back to Ad Accounts listing", ad_accounts_path %>

</div>

app/views/data_source/ad_accounts/custom_audiences/_create_modal.html.erb
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :custom_audience,
        method: :post,
        class: "form-inline",
        url: data_source_ad_accounts_custom_audiences_path do |f|
      %>
        <div class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.hidden_field :ad_act_id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Create</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('#create-modal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget); // Button that triggered the modal
    var adActId = button.data('ad-act-id'); // Extract info from data-* attributes
    var modal = $(this);
    modal.find('.modal-title').text('Create new Custom Audience');
    modal.find('.modal-body #custom_audience_ad_act_id').val(adActId);
  })
</script>

app/views/data_source/ad_accounts/custom_audiences/_upload_modal.html.erb
<div class="modal fade" id="upload-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :add_workflow_ids_to_custom_audience,
        method: :post,
        url: data_source_ad_accounts_custom_audiences_workflows_path do |f|
      %>
        <div class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= f.text_field :workflow_ids %>
          <%= f.hidden_field :custom_audience_id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('#upload-modal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget); // Button that triggered the modal
    var id = button.data('id'); // Extract info from data-* attributes
    var workflowIds = button.data("workflow-ids");
    var modal = $(this);
    modal.find('.modal-title').text('Add Workflow IDs to Custom Audience ' + id);
    modal.find('.modal-body #add_workflow_ids_to_custom_audience_workflow_ids').val(workflowIds);
    modal.find('.modal-body #add_workflow_ids_to_custom_audience_custom_audience_id').val(id);

  })
</script>

app/views/data_source/ad_accounts/custom_audiences/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <th>Ad Account ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Approximate Count</th>
      <th>Operation Status</th>
      <th>Delivery Status</th>
      <th>Workflows</th>
      <th></th>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result[:ad_act_id] %></td>
          <td><%= result[:name] %></td>
          <td><%= result[:description] %></td>
          <td><%= result[:approximate_count] %></td>
          <td><%= result[:operation_status] %></td>
          <td><%= result[:delivery_status] %></td>
          <td><%= result[:workflow_ids].join(", ") %></td>
          <td>
            <%= link_to "Edit", "#", class: "btn btn-primary",
              "data-id": "#{result[:id]}",
              "data-workflow-ids": "#{result[:workflow_ids]}",
              "data-toggle": "modal",
              "data-target": "#upload-modal"
            %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="modal fade" id="upload-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for :add_workflow_ids_to_custom_audience,
        method: :post,
        url: data_source_ad_accounts_custom_audiences_workflows_path do |f|
      %>
        <div class="modal-header">
          <h5 class="modal-title"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= f.text_field :workflow_ids %>
          <%= f.hidden_field :custom_audience_id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      <% end %>
    </div>
  </div>
  <script>
    $('#upload-modal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget); // Button that triggered the modal
      var id = button.data('id'); // Extract info from data-* attributes
      var workflowIds = button.data("workflow-ids");
      var modal = $(this);
      modal.find('.modal-title').text('Add Workflow IDs to Custom Audience ' + id);
      modal.find('.modal-body #add_workflow_ids_to_custom_audience_workflow_ids').val(workflowIds);
      modal.find('.modal-body #add_workflow_ids_to_custom_audience_custom_audience_id').val(id);

    })
  </script>
</div>

app/views/data_source/ad_accounts/custom_audiences/show.html.erb
<div class="container">
  <table class="table">
    <thead>
      <th>Name</th>
      <th>Approximate Count</th>
      <th>Operation Status</th>
      <th>Delivery Status</th>
      <th>Workflows</th>
      <th></th>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result[:name] %></td>
          <td><%= number_with_delimiter result[:approximate_count] %></td>
          <td><%= result[:operation_status] %></td>
          <td><%= result[:delivery_status] %></td>
          <td><%= result[:workflow_ids].join(", ") %></td>
          <td>
            <%= link_to "Edit", "#", class: "btn btn-primary",
              "data-id": "#{result[:id]}",
              "data-workflow-ids": "#{result[:workflow_ids]}",
              "data-toggle": "modal",
              "data-target": "#upload-modal"
            %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan=7>
          <%= link_to "New Custom Audience", "#", class: "btn btn-success",
            "data-toggle": "modal",
            "data-ad-act-id": "#{@results.first[:ad_act_id]}",
            "data-target": "#create-modal"
          %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<%= render "upload_modal" %>

<%= render "create_modal" %>

app/views/home/index.html.erb
<% if current_user %>
<% end %>